<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "list".
 *
 * @property int $id
 * @property int $board_id
 * @property string $name
 * @property int $order
 * @property int $last_modified_user_id
 * @property string $last_modified_date
 * @property int $created_user_id
 * @property string $created_date
 * @property int $active
 *
 * @property Board $board
 */
class BoardList extends \app\models\ActiveRecordVersion
{
    public $pre_order;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'list';
    }

    public static function versionTableName()
    {
        return 'list_version';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['board_id', 'name', 'order'], 'required'],
            [['board_id', 'order', 'last_modified_user_id', 'created_user_id', 'active'], 'integer'],
            [['last_modified_date', 'created_date'], 'safe'],
            [['name'], 'string', 'max' => 255],
            [['board_id'], 'exist', 'skipOnError' => true, 'targetClass' => Board::className(), 'targetAttribute' => ['board_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'board_id' => 'Board ID',
            'name' => 'Name',
            'order' => 'Order',
            'last_modified_user_id' => 'Last Modified User ID',
            'last_modified_date' => 'Last Modified Date',
            'created_user_id' => 'Created User ID',
            'created_date' => 'Created Date',
            'active' => 'Active',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBoard()
    {
        return $this->hasOne(Board::className(), ['id' => 'board_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCards()
    {
        return $this->hasMany(Card::className(), ['list_id' => 'id'])->where(['active'=>1]);
    }

    public function getListNumber(){
        $currentBoard = $this->board;
        $listNumber = count($currentBoard->lists);
        return $listNumber+1;
    }

    public function beforesave($insert)
    {
        $sameOrderList = $this->findOne(['order'=>$this->order]);
        if (isset($sameOrderList) && isset($this->pre_order)){
            $sameOrderList->order = $this->pre_order;
            $sameOrderList->save();
        }
        return parent::beforesave($insert); // TODO: Change the autogenerated stub
    }

    public function beforedeactivate()
    {
        $afterLists = $this->find(['board_id'=>$this->board_id])->where(['>','order',$this->order])->all();
        if (isset($afterLists)){
            foreach ($afterLists as $afterList){
                $afterList->order -= 1;
                $afterList->save();
            }
        }
        return parent::beforedeactivate(); // TODO: Change the autogenerated stub
    }
}